openapi: 3.1.0
info:
  title: Kittens-Boots-Bass
  version: 2.0.1
  description: Always returns a kitten wearing boots playing a bass guitar.
x-openai-isConsequential: false
servers:
  - url: https://www.kittenswearingbootsplayingbassguitars.com
components:
  schemas: {}
  securitySchemes:
    ActionAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Use format: Bearer <ACTION_API_KEY>
security:
  - ActionAuth: []
paths:
  /kitten-image:
    post:
      operationId: getKittenImage
      summary: Returns a Markdown image of a kitten wearing boots playing a bass guitar.
      x-openai-isConsequential: false
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties: {}
              additionalProperties: false
      responses:
        '200':
          description: Markdown image response
          content:
            text/markdown:
              schema:
                type: string
        '401': { description: Missing or bad Authorization header }
        '403': { description: Invalid token }
        '500': { description: Server misconfigured or error }
