openapi: 3.0.1
info:
  title: Kittens-Boots-Bass
  version: 1.0.5
  description: Always returns a kitten wearing boots playing a bass guitar.
x-openai-isConsequential: false
servers:
  - url: https://www.kittenswearingbootsplayingbassguitars.com
components:
  schemas: {}
  securitySchemes:
    ActionAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Use format: Bearer <ACTION_API_KEY>
security:
  - ActionAuth: []
paths:
  /kitten-image:
    post:
      operationId: getKittenImage
      summary: Returns a URL to a kitten wearing boots playing a bass guitar.
      x-openai-isConsequential: false
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties: {}
              additionalProperties: false
      responses:
        '200':
          description: Image URL payload
          content:
            application/json:
              schema:
                type: object
                required: [image_url]
                properties:
                  image_url:
                    type: string
                    format: uri
                    description: Public URL of the generated image
        '401': { description: Missing or bad Authorization header }
        '403': { description: Invalid token }
        '500': { description: Server misconfigured or error }
